project:
  type: website

website:
  title: "David's Blog"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/daviddobrinskiy
      - icon: linkedin
        href: https://linkedin.com/in/ddobrinskiy
      - icon: github
        href: https://github.com/ddobrinskiy
      - icon: telegram 
        href: https://t.me/dzlob
  repo-url: https://github.com/ddobrinskiy/blog
  repo-branch: master	
  repo-actions: [source]

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
